module PostProperties exposing
    ( MonotoneWitness
    , PropertyResult
    , monotone
    )

import Bitwise
import BoolFun exposing (BF)


type alias PropertyResult a =
    { holds : Bool
    , witness : Maybe a
    }


type alias MonotoneWitness =
    { smaller : Int
    , bigger : Int
    }


{-| A function f is monotone iff for every covering pair x ⋖ y in {0,1}^n
(y differs from x by flipping a single 0-bit to 1), f(x) ≤ f(y).
Equivalently: there is no covering pair with f(x)=1 and f(y)=0.

Iterating only covering pairs (not arbitrary x < y) is sufficient because
the order on {0,1}^n is generated by them — and gives a minimal,
visually adjacent witness when the property fails.

-}
monotone : BF -> PropertyResult MonotoneWitness
monotone bf =
    let
        arity =
            BoolFun.arityOf bf

        coveringPairs =
            BoolFun.inputs arity
                |> List.concatMap
                    (\x ->
                        List.range 0 (arity - 1)
                            |> List.filterMap
                                (\k ->
                                    let
                                        bitMask =
                                            Bitwise.shiftLeftBy k 1
                                    in
                                    if Bitwise.and x bitMask == 0 then
                                        Just { smaller = x, bigger = Bitwise.or x bitMask }

                                    else
                                        Nothing
                                )
                    )

        firstViolation =
            coveringPairs
                |> List.filter
                    (\{ smaller, bigger } ->
                        BoolFun.eval bf smaller && not (BoolFun.eval bf bigger)
                    )
                |> List.head
    in
    case firstViolation of
        Just w ->
            { holds = False, witness = Just w }

        Nothing ->
            { holds = True, witness = Nothing }
